spring:
  application:
    name: autobot-res
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/autobot?useSSL=true
    username: root
    password: SRTAgsMeW}gQ@ac
    #password: '{cipher}AQAelpzn/tGihbTOaBticSBtfGWU5ryBmwQVSHCAk/FTVWlmhSY6Zewnt1MNUOBK5ZdHfVHmiCFvGnGzpxpotl4pr5QlcfI53LhWf2vT/In6beHaY5/CK5zGywTEWZdADpufVPS+EeXcUBgmYzwbRPDQtLmKyJ05S9jXtbKU4HtFaHSggaM15tJMo83sHpMG/+rxECWPTgjYzimUqm2aubqIi4qd2ejv7bcDB3kCUT4PnQ7v5f+ndqKn97eqRHGVHwVg5r5v7ZkVD6fFxXHfe02B5svBoDFe8O7cyrNau/LrCNqewPN0g1l4Hz3eM1hFkSuz+zrVFJojT3Jj3LV2L/WGi56MYZG8Q9NQAYJzBzKalGBfdD9U0usVdVe7tc8nDls='
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      max-active: 20
    
server:
  port: 8010
  session:
    timeout: 10
  tomcat:
    uri-encoding: UTF-8
    
mybatis:
  mapper-locations:
  - classpath:mapping/*/*.xml     
  
eureka:
  instance:
    prefer-ip-address: true # 注册时使用ip而不是主机名
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/,http://127.0.0.2:8000/eureka/
      
from: git-dev-1.0.2
to: '{cipher}AQDH3kZfSeyIdkhK8MdzlUPDRaAgbgYTZ+RwbJtr3kQ6CejctznhHDHZVE5EkmZBej8k+ke2d+DF7Wybz+NwrAKKy8hmNPbYdMltm92nquvEQZpRWAyYtjSt+gG49Ipd4F1b9yNMCogyFeaWBwYl1bbnRSsJJTpjaTGuxVFdWmhMhBncAVWC107tCNRYD7m+6b74kQpKyXlFFC14Lo1W4+l2+ycSxKJLCde16wlTjhT1YmHtP6jjo58/Dh6FzSNnPegVYeWGnjFuzfzBhNpFz4f4gi+DDvZx3GDO9CylEnkl071LSTvWCMSijT9/lq5kLcbrqhXqJw0yjYahAuvJi+PPJalFsyKoATuRJTvEb/Sgh3FC3wMReuV3ad5CAi/ZFZY='


     
