spring:
  application:
    name: auto
  
    
server:
  port: 8403
  session:
    timeout: 10
  tomcat:
    uri-encoding: UTF-8
  
eureka:
  client:
    service-url:
      defaultZone: http://www.lxdyun.com:7100/eureka/
      
from: git-test-1.0